# This is a workflow that update Vermilion Frontend
name: 1. Config Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hetzner_server:
        description: 'Which server to deploy to? Hetzner_blue or Hetzner_green'
        required: true
        default: 'Hetzner_'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Config-Deploy:
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.hetzner_server }}'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}
        
      - name: Create AWS config file
        run: ssh staging 'mkdir -p .aws; echo "[default]" > ~/.aws/config;'
      
      - name: Create AWS credential file
        run: ssh staging 'printf "%s\n" "[default]"
                                         "aws_access_key_id=${{secrets.S3_ACCESS_KEY}}"
                                         "aws_secret_access_key=${{secrets.S3_SECRET_ACCESS_KEY}}" > ~/.aws/credentials'

      - name: Create rclone config file
        run: ssh staging 'printf "%s\n" "[r2]"
                                         "type = s3"
                                         "provider = Cloudflare"
                                         "access_key_id = ${{secrets.R2_ACCESS_KEY}}"
                                         "secret_access_key = ${{secrets.R2_SECRET_ACCESS_KEY}}"
                                         "region = auto"
                                         "endpoint = https://${{secrets.CF_ACCOUNT_ID}}.r2.cloudflarestorage.com"
                                         "bucket_acl = private"
                                         "no_check_bucket = true" > ~/.config/rclone/rclone.conf'


      - name: Create Ord config file
        run: ssh staging 'printf "%s\n" "${{format('s3_bucket_name{0} ', ':')}}vermilion-ordinals"
                                        "${{format('s3_head_check{0} ', ':')}}true"
                                        "${{format('s3_upload_start_number{0} ', ':')}}1000000000"
                                        "${{format('db_host{0} ', ':')}}localhost"
                                        "${{format('db_name{0} ', ':')}}vermilion"
                                        "${{format('db_user{0} ', ':')}}${{secrets.MYSQL_USER}}"
                                        "${{format('db_password{0} ', ':')}}${{secrets.MYSQL_PASS}}"
                                        "${{format('magiceden_api_key{0} ', ':')}}${{secrets.MAGICEDEN_KEY}}"
                                        "${{format('access_token_secret{0} ', ':')}}${{secrets.JWT_ACCESS_TOKEN_SECRET}}"
                                        "${{format('index_runes{0} ', ':')}}true"
                                        "hidden:" > ~/ord.yaml'
      
      # ssh-keygen -t ed25519 -C "miltu.s.nayak@gmail.com"
      - name: Add Github SSH key and adjust permissions
        run: |
          ssh staging 'echo "${{secrets.SERVER_GITHUB_SSH_KEY}}" > ~/.ssh/id_ed25519; chmod 700 ~/.ssh/; chmod 600 ~/.ssh/id_ed25519;'
          ssh staging 'echo "${{secrets.SERVER_GITHUB_SSH_KEY_ORD}}" > ~/.ssh/id_ed25519_ord; chmod 700 ~/.ssh/; chmod 600 ~/.ssh/id_ed25519_ord;'
          ssh staging 'echo "${{secrets.SERVER_GITHUB_SSH_KEY_DISCOVER}}" > ~/.ssh/id_ed25519_discover; chmod 700 ~/.ssh/; chmod 600 ~/.ssh/id_ed25519_discover;'
          ssh staging 'set +o noclobber; ssh-keyscan -t ed25519 github.com > ~/.ssh/known_hosts || echo "Known_hosts already exists. Not adding."; set -o noclobber; '        
      
      - name: Check out the new code from Github
        run: |
          ssh staging 'if [ -d "Vermilion" ]; then 
            git -C Vermilion fetch && 
            git -C Vermilion checkout ${{ github.ref_name }} && 
            git -C Vermilion reset --hard origin/${{ github.ref_name }}; 
          else 
            git clone -b ${{ github.ref_name }} git@github.com:SmarakNayak/Vermilion.git; 
          fi'
      
      - name: Setup ssh config
        run: ssh staging 'sudo cp Vermilion/Config/ssh.conf ~/.ssh/config;'
      
      - name: Setup nginx config
        run: |
          ssh staging 'sudo cp Vermilion/nginx/server.conf /etc/nginx/conf.d/server.conf;' 
          ssh staging 'sudo cp Vermilion/nginx/nginx.conf /etc/nginx/nginx.conf;'
          ssh staging 'sudo rm -f /etc/nginx/sites-enabled/default;'
      
      - name: Setup postgres config
        run: |
          ssh staging 'sudo cp Vermilion/postgres/postgresql.conf /etc/postgresql/17/main/postgresql.conf;'
          ssh staging 'sudo cp Vermilion/postgres/pg_hba.conf /etc/postgresql/17/main/pg_hba.conf;'
          #                                 TYPE DB  USER    ADDRESS                          METHOD
          ssh staging 'sudo bash -c "echo \"host all all ${{ vars.ALTERNATE_SERVER_HOST }}/32 scram-sha-256\" >> /etc/postgresql/17/main/pg_hba.conf";'

      - name: Setup chromium sandbox config
        run: |
          ssh staging 'sudo cp Vermilion/Config/chrome-dev-builds /etc/apparmor.d/chrome-dev-builds;'
          ssh staging 'sudo service apparmor reload;'

      # Note: '"'"' = escaped single ' - bash implicitly concatenates differently quoted string expressions
      - name: Init postgres server
        run: |
          ssh staging 'sudo --login -u postgres createuser ${{secrets.MYSQL_USER}} || echo "user already exists"'
          ssh staging 'sudo --login -u postgres createdb vermilion || echo "db already exists"'
          ssh staging 'sudo --login -u postgres psql -d vermilion -c "alter user ${{secrets.MYSQL_USER}} with encrypted password '"'"'${{secrets.MYSQL_PASS}}'"'"'"';
          ssh staging 'sudo --login -u postgres psql -d vermilion -c "grant all privileges on database vermilion to ${{secrets.MYSQL_USER}}"';
          ssh staging 'sudo --login -u postgres psql -d vermilion -c "GRANT ALL ON SCHEMA public TO ${{secrets.MYSQL_USER}}"';

      - name: Setup cronjobs
        run: |
          ssh staging 'mkdir -p bin; cp /home/ubuntu/Vermilion/Cronjobs/social_schema_backup.sh /home/ubuntu/bin/social_schema_backup.sh; chmod +x /home/ubuntu/bin/social_schema_backup.sh;'
          ssh staging 'crontab /home/ubuntu/Vermilion/Cronjobs/Vermilion.cron'