# This is a workflow that deploys a fresh bitcoin node
name: 2. Hetzner Bitcoin Deploy.yml

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Bitcoin-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}

      - name: Stop the server if running
        run: |
          ssh staging 'sudo systemctl is-active bitcoind && sudo systemctl stop bitcoind || echo "bitcoind not running";'
      
      # Installs bitcoin if not already installed
      - name: Install bitcoin-core 
        run: ssh staging '[ -d "bitcoin_install" ] && [ "$(cat bitcoin_install/version)" == "26.0" ] && echo "Bitcoin core already installed" 
                                                   || (wget https://bitcoincore.org/bin/bitcoin-core-26.0/bitcoin-26.0-x86_64-linux-gnu.tar.gz
                                                       && mkdir -p ~/bitcoin_install 
                                                       && rm -f ~/bitcoin_install/* 
                                                       && tar -xzf bitcoin-*.tar.gz -C ~/bitcoin_install --strip-components 1 
                                                       && rm bitcoin-*.tar.gz
                                                       && echo "26.0" > ~/bitcoin_install/version);'

      - name: Set up systemd services
        run: ssh staging 'sudo cp Vermilion/systemd/bitcoind.service /etc/systemd/system/bitcoind.service; sudo systemctl daemon-reload;' 
      
      - name: Start the bitcoin service
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start bitcoind.service;'
