# This is a workflow that update Vermilion Frontend
name: 5. Frontend Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hetzner_server:
        description: 'Which server to deploy to? Hetzner_blue or Hetzner_green'
        required: true
        default: 'Hetzner_'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Frontend-Deploy:
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.hetzner_server }}'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}  
      
      - name: Check out the new code from Github
        run: |
          ssh staging 'if [ -d "Vermilion" ]; then 
            git -C Vermilion fetch && 
            git -C Vermilion checkout ${{ github.ref_name }} && 
            git -C Vermilion reset --hard origin/${{ github.ref_name }}; 
          else 
            git clone -b ${{ github.ref_name }} git@github.com:SmarakNayak/Vermilion.git; 
          fi'
      
      - name: Setup nginx config
        run: |
          ssh staging 'sudo cp Vermilion/nginx/server.conf /etc/nginx/conf.d/server.conf;' 
          ssh staging 'sudo cp Vermilion/nginx/nginx.conf /etc/nginx/nginx.conf;'
          ssh staging 'sudo rm -f /etc/nginx/sites-enabled/default;'
        
      - name: Install bun
        run: ssh staging 'curl -fsSL https://bun.sh/install | bash;'

      - name: Build Frontend
        run: ssh staging 'cd Vermilion/app; /home/ubuntu/.bun/bin/bun install; /home/ubuntu/.bun/bin/bun run build;'

      - name: Setup Bun server
        run: ssh staging 'cd Vermilion/app/server; /home/ubuntu/.bun/bin/bun install;'
     
      - name: Configure Bun service
        run: ssh staging 'sudo cp Vermilion/systemd/bun.service /etc/systemd/system/; sudo systemctl daemon-reload;'

      - name: Set up static files
        run: ssh staging 'sudo rm -r /var/www/html/*; sudo cp -r ~/Vermilion/app/dist/. /var/www/html/; sudo cp -r ~/Vermilion/app/public/. /var/www/html/;'
      
      - name: Restart nginx
        run: ssh staging 'sudo systemctl is-active nginx.service && sudo systemctl restart nginx.service || sudo systemctl start nginx.service;'

      - name: Restart bun
        run: ssh staging 'sudo systemctl is-active bun.service && sudo systemctl restart bun.service || sudo systemctl start bun.service;'
