# This is a workflow that promotes one server to primary and demotes the other to secondary
name: 7. Hetzner Blue Green Switchover

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hetzner_promote_server:
        description: 'Which server to promote? Hetzner_blue or Hetzner_green'
        required: true
        default: 'Hetzner_'
      hetzner_demote_server:
        description: 'Which server to demote? Hetzner_blue or Hetzner_green'
        required: true
        default: 'Hetzner_'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Promote-Secondary: ## promoting secondary works by enabling sub on current primary
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.hetzner_demote_server }}'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}

      - name: Set secondary server color
        run: echo "SECONDARY_SERVER_COLOR=$(echo ${{ github.event.inputs.hetzner_promote_server }} | sed 's/Hetzner_//')" >> $GITHUB_ENV
        
      - name: Promote Secondary 
        run: ssh staging 'PGPASSWORD=${{secrets.MYSQL_PASS}} psql -U ${{ secrets.MYSQL_USER }} -d vermilion -h localhost -c "ALTER SUBSCRIPTION social_sub_to_${{env.SECONDARY_SERVER_COLOR}} ENABLE;"'
  
  ## switch traffic goes here
  
  Demote-Primary: ## demoting primary works by disabling sub on current secondary
    runs-on: ubuntu-latest
    environment: '${{ github.event.inputs.hetzner_promote_server }}'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}
      
      - name: Set primary server color
        run: echo "PRIMARY_SERVER_COLOR=$(echo ${{ github.event.inputs.hetzner_demote_server }} | sed 's/Hetzner_//')" >> $GITHUB_ENV

      - name: Demote Primary 
        run: ssh staging 'PGPASSWORD=${{secrets.MYSQL_PASS}} psql -U ${{ secrets.MYSQL_USER }} -d vermilion -h localhost -c "ALTER SUBSCRIPTION social_sub_to_${{env.PRIMARY_SERVER_COLOR}} DISABLE;"'


          