# This is a workflow that update Vermilion Frontend
name: Vermilion Frontend Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Vermilion-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}

      - name: Stop nginx if running
        run: |
          ssh staging 'sudo systemctl is-active nginx.service && sudo systemctl stop nginx.service || echo "nginx not running";'
      
      # ssh-keygen -t ed25519 -C "miltu.s.nayak@gmail.com"
      - name: Add Github SSH key and adjust permissions
        run: |
          ssh staging 'echo "${{secrets.SERVER_GITHUB_SSH_KEY}}" > ~/.ssh/id_ed25519_vermilion; chmod 700 ~/.ssh/; chmod 600 ~/.ssh/id_ed25519_vermilion;' # Doesn't work unless secret is referred to using braces, possibly due to single quotes
          ssh staging 'set +o noclobber; ssh-keyscan -t ed25519 github.com > ~/.ssh/known_hosts || echo "Known_hosts already exists. Not adding."; set -o noclobber; '        
      
      - name: Check out the new code from Github
        run: ssh staging 'git -C Vermilion fetch && git -C Vermilion reset --hard origin/main || git clone git@github-vermilion:SmarakNayak/Vermilion.git' # This pulls if directory exists, otherwise clones
      
      - name: Setup nginx config
        run: ssh staging 'sudo cp Vermilion/nginx/server.conf /etc/nginx/conf.d/server.conf;'

      - name: Install node 20.4.0
        run: ssh staging 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash; . ~/.nvm/nvm.sh; nvm install 20.4.0;'
  
      - name: Install client node dependencies
        run: ssh staging 'cd Vermilion/app; . ~/.nvm/nvm.sh; npm install; npm run build;'
        
      - name: Set up static files
        run: ssh staging 'sudo rm -r /var/www/html/*; sudo cp -r ~/Vermilion/app/build/. /var/www/html/;'
      
      - name: Restart nginx
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start nginx.service;'
