# This is a workflow that adds manual content moderation
name: Vermilion Content Override

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Vermilion-Content-Override:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}

      - name: Check out the new code from Github
        run: ssh staging 'git -C Vermilion-Discover fetch && git -C Vermilion-Discover reset --hard origin/main || git clone git@github-vermilion:SmarakNayak/Vermilion-Discover.git' # This pulls if directory exists, otherwise clones

      - name: Get python dependencies
        run: |
          ssh staging 'sudo apt-get install -y python3-venv'
          ssh staging 'cd Vermilion-Discover; python3 -m venv venv;'
          ssh staging 'cd Vermilion-Discover; source venv/bin/activate; python3 -m pip install -r requirements.txt'

      - name: Run the override script
        run: ssh staging 'cd Vermilion-Discover; source venv/bin/activate; export DISCOVER_CONFIG_PATH=/home/ubuntu/ord.yaml; python3 override.py;'
