# This is a workflow that deploys a fresh vermilion instance
name: Vermilion Restore

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Vermilion-Restore:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ vars.SERVER_HOST }}
          
      - name: Install AWS CLI
        run: |
          ssh staging 'sudo apt-get -y update'
          ssh staging 'sudo apt-get -y install awscli'
        
      - name: Create AWS config file
        run: ssh staging 'mkdir -p .aws; echo "[default]" > ~/.aws/config;'
      
      - name: Create AWS credential file
        run:  ssh staging 'printf "%s\n" "[default]"
                                         "aws_access_key_id=${{secrets.S3_ACCESS_KEY}}"
                                         "aws_secret_access_key=${{secrets.S3_SECRET_ACCESS_KEY}}" > ~/.aws/credentials'

      - name: Kick off recovery
        run: |
          ssh staging 'mkdir -p .lnd; mkdir -p .bitcoin;'
          ssh staging 'nohup aws s3 sync s3://newro-lightning-backup/.bitcoin .bitcoin --delete --exact-timestamps &>bitcoin_backup.log &'
